AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Parameters:
  VpcCidrBlock:
    Description: "Input VPC CIDR Block"
    Type: String
    Default: "10.100.0.0/22"

  EcsSubnetAzACidrBlock:
    Description: "Input ECS AzA subnet CIDR Block"
    Type: String
    Default: "10.100.0.0/28"

  EcsSubnetAzCCidrBlock:
    Description: "Input ECS AzC subnet CIDR Block"
    Type: String
    Default: "10.100.0.16/28"

  AlbSubnetAzACidrBlock:
    Description: "Input ECS AzA subnet CIDR Block"
    Type: String
    Default: "10.100.0.32/28"

  AlbSubnetAzCCidrBlock:
    Description: "Input ECS AzC subnet CIDR Block"
    Type: String
    Default: "10.100.0.64/28"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: "sample-vpc"

  EcsAzASubent:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      VpcId: !Ref VPC
      CidrBlock: !Ref EcsSubnetAzACidrBlock
      Tags:
        - Key: Name
          Value: "sample-ecs-subnet-1a"

  EcsAzCSubent:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      VpcId: !Ref VPC
      CidrBlock: !Ref EcsSubnetAzCCidrBlock
      Tags:
        - Key: Name
          Value: "sample-ecs-subnet-1c"

  AlbAzASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      VpcId: !Ref VPC
      CidrBlock: !Ref AlbSubnetAzACidrBlock
      Tags:
        - Key: Name
          Value: "sample-alb-subnet-1a"

  AlbAzCSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      VpcId: !Ref VPC
      CidrBlock: !Ref AlbSubnetAzCCidrBlock
      Tags:
        - Key: Name
          Value: "sample-alb-subnet-1c"

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: VpcId

  EcsAzASubentId:
    Value: !Ref EcsAzASubent
    Export:
      Name: EcsAzASubentId

  EcsAzCSubentId:
    Value: !Ref EcsAzCSubent
    Export:
      Name: EcsAzCSubentId

  AlbAzASubnetId:
    Value: !Ref AlbAzASubnet
    Export:
      Name: AlbAzASubnetId

  AlbAzCSubnetId:
    Value: !Ref AlbAzCSubnet
    Export:
      Name: AlbAzCSubnetId
